// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi_4wUEgQWJQG8vFnTvH_RT8oNuJuHfzY',
    appId: '1:669657050623:web:011f8d0c7bfc293f640bca',
    messagingSenderId: '669657050623',
    projectId: 'kitaplar-odev',
    authDomain: 'kitaplar-odev.firebaseapp.com',
    storageBucket: 'kitaplar-odev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk-dzOQwBC8iajCOfkFVJPOlMzV0pha8M',
    appId: '1:669657050623:android:52beb06c6d772652640bca',
    messagingSenderId: '669657050623',
    projectId: 'kitaplar-odev',
    storageBucket: 'kitaplar-odev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUxdQHWL7AksTz01cFhI0NJ79KoyVQy7Y',
    appId: '1:669657050623:ios:46a546f4861b6095640bca',
    messagingSenderId: '669657050623',
    projectId: 'kitaplar-odev',
    storageBucket: 'kitaplar-odev.appspot.com',
    iosBundleId: 'com.example.odev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUxdQHWL7AksTz01cFhI0NJ79KoyVQy7Y',
    appId: '1:669657050623:ios:4c49a73bce852c74640bca',
    messagingSenderId: '669657050623',
    projectId: 'kitaplar-odev',
    storageBucket: 'kitaplar-odev.appspot.com',
    iosBundleId: 'com.example.odev.RunnerTests',
  );
}
